import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/">홈</Link> |<Link href="/login"> 로그인</Link>
        {children}
      </body>
    </html>
  );
}
